### ISSUE TITLE
Tweak readme.MD

### ISSUE THREAD

**Issue by hellracer** [jcmoraisjr/modsecurity-spoa#1]
Hey,

first of all would like to say thanks a ton for sharing this to the world, but could you please tweak the commandline on running the agent for some people don't know to expose docker service

`$ docker run quay.io/jcmoraisjr/modsecurity-spoa [options] [-- <config-file1> [<config-file2> ...] ]`
into 
`$ docker run -p 12345:12345 quay.io/jcmoraisjr/modsecurity-spoa [options] [-- <config-file1> [<config-file2> ...] ]`
`

just my 0.2$

**Comment by jcmoraisjr** [comment]
Hi, sure, done. Even though this is a small piece of a more complex deployment and one would need to have some skills in order to successfully deploy modsec-spoa. Closing.
