### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by GMartinez-Sisti** [jcmoraisjr/modsecurity-spoa#2]
Hi @jcmoraisjr,

Great work on this project.

Are there any plans to update modsecurity and haproxy versions? I can send a pull request if you like, but would like to know how you test this.

Regards

**Comment by jcmoraisjr** [comment]
Hi thanks! PRs always welcome, I test it configuring a haproxy and a valid request (eg `/`) and an invalid one (eg `/?p=/etc/passwd`). [Here](https://haproxy-ingress.github.io/docs/examples/modsecurity/#test) is the requests issued and expected behaviour.

**Comment by GMartinez-Sisti** [comment]
Hi!

PR sent -> https://github.com/jcmoraisjr/modsecurity-spoa/pull/3

**Comment by jcmoraisjr** [comment]
Merged and published as v0.5. Closing.
