### ISSUE TITLE
Feature Request: Multi-Platform Image

### ISSUE THREAD

**Issue by s1rc** [jcmoraisjr/modsecurity-spoa#40]
Thank you for all your hard work, we have been using ModSecurity with your HAProxy Ingress chart for a while.

We recently migrated our cluster to `arm64`, so in order to continue to use ModSecurity to use with HAProxy, we need to maintain our own container image based on your `https://github.com/jcmoraisjr/modsecurity-spoa/blob/master/rootfs/Dockerfile`. 

Would it be possible to add `linux/arm64` as a platform in your image?

**Comment by jcmoraisjr** [comment]
Wondering why I didn't configure it before. Please give `quay.io/jcmoraisjr/modsecurity-spoa:v0.12-beta.2` a try and I'll tag v0.12 after that.

**Comment by s1rc** [comment]
@jcmoraisjr trying on staging, so far so good! 👍 🙇

**Comment by jcmoraisjr** [comment]
v0.12 already tagged, closing.
